# Generated by Django 4.2.29 on 2026-03-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('CHECKED_IN', 'Checked In'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('CheckIn_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='checkin_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='api.booking')),
            ],
        ),
    ]
