# Generated by Django 4.2.29 on 2026-03-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_status_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='photo',
        ),
    ]
